basicEnabled: true
basic:
  replicaCount: 1
  
  image:
    repository: "ghcr.io/yuryklimchuk"
    tag: "prodms/warehouse-server"
    version: "1.0.0-SNAPSHOT"
    pullPolicy: Always
  
  app:
    id: "warehouse"
    port: 8080

  env:
    valuesFromSecretRef:
      - name: MONGO_CONNECTION_STRING
        secretName: prodms-mongodb-admin-mongodb-user
        key: connectionString.standard

kafka:
  url: "prodms-kafka-cluster-kafka-bootstrap.prodms-infra:9092"
mongo:
  connection:
    mode: 15
